spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: omgd45945.+
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters:
        - stat
        - wall
      max-active: 12