spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: omgd45945.+
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: wall,stat
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1
        enabled: true
      wall:
        enabled: true
        config:
          drop-table-allow: false

    druid:
      aop-patterns: com.ren.admin.*

      stat-view-servlet:
        enabled: true
        login-username: 123
        login-password: 123123
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

    #druid:
    #  filters:
    #    - stat
    #    - wall
    #  max-active: 12
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8888/
        instance:
          prefer-ip: true  # 使用ip注册进来

  application:
    name: boot-05-web-admin

# 配置 mybatis 规则
#mybatis:
#  # 可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中
#  # config-location: classpath:mybatis-config.xml
#  # mapper-locations: classpath:com/ren/admin/mapper/*.xml
#  configuration:        # configuration 不能与 config-location 同时存在，所以一旦选择yaml配置就不能用配置文件配置
#    map-underscore-to-camel-case: true   # 开启驼峰命名法

# 配置 mybatis-plus 规则
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true   # 开启驼峰命名法
  type-aliases-package: com.ren.admin.entity   # 开启类到配置文件映射

# management 是所有actuator的配置
# management.endpoint.端点名.xxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  # false 默认关闭所有监控端口 true 则相反
    web:
      exposure:
        include: "*"  # 以web方式暴漏所有端口
  endpoint:
    # 这之下每一个监控端口都可以分开调节与开启
    health:
      show-details: always   # 暴漏health下的所有详细配置
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

  info:
    env:
      enabled: true

info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
