spring:
  mvc:
  #给静态资源的访问路径加上了前缀
  #    static-path-pattern: /res/**
    # 开启页面表单的Rest功能
    hiddenmethod:
      filter:
        enabled: true

    contentnegotiation:
      favor-parameter: true   # 开启请求参数内容协商模式


  web:
    resources:
      #自定义静态资源位置
      static-locations: classpath:/haha/
      #自定义静态资源缓存时间
      cache:
        period: 11000

